export const marketplaceItems = [
  { id: 'bored-ape', title: 'Bored Ape Yacht Club', creator: 'Yuga Labs', creatorHandle: '@yugalabs', price: 28, displayPrice: '28 ETH', category: 'Collectibles', image: '/assets/bored-ape-yacht-club-banner.webp', chain: 'Ethereum', tokenId: '#8817', collection: 'Bored Ape Yacht Club', description: 'A membership pass to one of the most recognizable communities in digital culture.', owners: 6421, editions: 10000, verified: true },
  { id: 'right-click', title: 'Right-Click', creator: 'XCOPY', creatorHandle: '@xcopy', price: 7, displayPrice: '$7.00M', category: 'Art', image: '/assets/10_rightclicksave_as.webp', chain: 'Ethereum', tokenId: '#1', collection: 'XCOPY', description: 'A high-voltage study in motion, noise, and the strange electricity of being online.', auction: true, endsIn: 42 * 60 * 60 + 18 * 60, owners: 1, editions: 1, verified: true },
  { id: 'blue-illusion', title: 'Blue Illusion', creator: 'Pak', creatorHandle: '@pak', price: 7.12, displayPrice: '$7.12M', category: 'Art', image: '/assets/blue_illusion.webp', chain: 'Ethereum', tokenId: '#707', collection: 'Lost Poets', description: 'An edition from one of digital art\'s most rigorous and elusive practices.', auction: true, endsIn: 19 * 60 * 60 + 42 * 60, owners: 12, editions: 20, verified: true },
  { id: 'bastard-gan-punk', title: 'Bastard Gan Punk', creator: 'Larva Labs', creatorHandle: '@larvalabs', price: 8.9, displayPrice: '$8.90M', category: 'Collectibles', image: '/assets/814.webp', chain: 'Ethereum', tokenId: '#5822', collection: 'CryptoPunks', description: 'A rare pixel portrait from the collection that helped define the NFT era.', auction: true, endsIn: 9 * 60 * 60 + 10 * 60, owners: 1, editions: 1, verified: true },
  { id: 'planet-fall', title: 'Planet Fall', creator: 'Refik Anadol', creatorHandle: '@refikanadol', price: 23.7, displayPrice: '$23.70M', category: 'Art', image: '/assets/planetfall.avif', chain: 'Ethereum', tokenId: '#04', collection: 'Machine Hallucinations', description: 'A living visual memory generated from planetary-scale data.', auction: true, endsIn: 71 * 60 * 60, owners: 4, editions: 10, verified: true },
  { id: 'bean-5467', title: 'Bean #5467', creator: 'BEANZ OFFICIAL', creatorHandle: '@beanz', price: 0.42, displayPrice: '0.42 ETH', category: 'Collectibles', image: '/assets/bean.avif', chain: 'Ethereum', tokenId: '#5467', collection: 'BEANZ', description: 'A tiny companion with a big personality.', owners: 2841, editions: 19950, verified: true },
  { id: 'oni-sakura', title: 'Oni Sakura', creator: 'Foundation', creatorHandle: '@foundation', price: 1.85, displayPrice: '1.85 ETH', category: 'Art', image: '/assets/oni.png', chain: 'Ethereum', tokenId: '#118', collection: 'Oni', description: 'Soft light, sharp edges, and a moment caught between seasons.', owners: 36, editions: 100, verified: true },
  { id: 'three-landers', title: 'Three Landers', creator: '3 Landers', creatorHandle: '@3landers', price: 2.1, displayPrice: '2.10 ETH', category: 'Art', image: '/assets/3 landers.avif', chain: 'Ethereum', tokenId: '#031', collection: '3 Landers', description: 'A signal from somewhere just beyond the horizon.', owners: 421, editions: 1000, verified: false },
  { id: 'otherside-meta', title: 'Otherside of Meta', creator: '#89275', creatorHandle: '@otherside', price: 0.9, displayPrice: '0.90 ETH', category: 'Virtual worlds', image: '/assets/vol.avif', chain: 'Ethereum', tokenId: '#89275', collection: 'Otherdeed', description: 'A place to build, explore, and make the impossible feel familiar.', owners: 12034, editions: 100000, verified: true },
  { id: 'fiji', title: 'FIJI', creator: 'Fiji NFT', creatorHandle: '@fiji', price: 3.3, displayPrice: '3.30 ETH', category: 'Photography', image: '/assets/fiji.avif', chain: 'Ethereum', tokenId: '#09', collection: 'Fiji', description: 'A blue-hour photograph with nowhere else to be.', owners: 18, editions: 50, verified: false },
  { id: 'seaport-subject', title: 'Seaport Subject', creator: 'Open Editions', creatorHandle: '@open-editions', price: 1.225, displayPrice: '1.225 ETH', category: 'Art', image: '/assets/seaport-subject.webp', chain: 'Ethereum', tokenId: '#241', collection: 'Open Editions', description: 'An archival fragment from a city in constant motion.', owners: 92, editions: 300, verified: false },
  { id: 'roboramen', title: 'RoboRamen', creator: 'RoboRamen', creatorHandle: '@roboramen', price: 1.2, displayPrice: '1.20 ETH', category: 'Collectibles', image: '/assets/RoboRamen.webp', chain: 'Ethereum', tokenId: '#77', collection: 'RoboRamen', description: 'Hot noodles, cold steel, and a robot with a midnight shift.', owners: 741, editions: 5000, verified: true },
  { id: 'ringers-109', title: 'Ringers #109', creator: 'Dmitri Cherniak', creatorHandle: '@dmitricherniak', price: 111.2, displayPrice: '111.20 ETH', category: 'Art', image: '/assets/9_ringers_109.webp', chain: 'Ethereum', tokenId: '#109', collection: 'Ringers', description: 'A generative composition built from a simple rule set and infinite possibility.', owners: 1, editions: 1, verified: true },
  { id: 'ringers-109-study', title: 'Ringers #109 / Study', creator: 'Dmitri Cherniak', creatorHandle: '@dmitricherniak', price: 4.8, displayPrice: '4.80 ETH', category: 'Art', image: '/assets/9_ringers_109.webp', chain: 'Ethereum', tokenId: '#109-S', collection: 'Ringers Studies', description: 'A signed study edition exploring the geometry behind Ringers #109.', owners: 22, editions: 64, verified: true },
  { id: 'planet-fall-dawn', title: 'Planet Fall: Dawn', creator: 'Refik Anadol', creatorHandle: '@refikanadol', price: 6.4, displayPrice: '6.40 ETH', category: 'Generative', image: '/assets/planetfall.avif', chain: 'Ethereum', tokenId: '#DWN', collection: 'Machine Hallucinations', description: 'The first light of a data-driven world, released as a limited moving-image edition.', owners: 48, editions: 250, verified: true },
  { id: 'fiji-afterlight', title: 'FIJI / Afterlight', creator: 'Fiji NFT', creatorHandle: '@fiji', price: 0.68, displayPrice: '0.68 ETH', category: 'Photography', image: '/assets/fiji.avif', chain: 'Ethereum', tokenId: '#AF7', collection: 'Fiji Editions', description: 'The last blue minute before the island goes dark.', owners: 76, editions: 120, verified: false },
  { id: 'bean-5467-shadow', title: 'Bean #5467 / Shadow', creator: 'BEANZ OFFICIAL', creatorHandle: '@beanz', price: 0.19, displayPrice: '0.19 ETH', category: 'Collectibles', image: '/assets/bean.avif', chain: 'Ethereum', tokenId: '#5467-S', collection: 'BEANZ', description: 'A monochrome companion edition for collectors who like their beans mysterious.', owners: 1054, editions: 5000, verified: true },
  { id: 'oni-sakura-print', title: 'Oni Sakura / Print', creator: 'Foundation', creatorHandle: '@foundation', price: 0.72, displayPrice: '0.72 ETH', category: 'Photography', image: '/assets/oni.png', chain: 'Ethereum', tokenId: '#118-P', collection: 'Oni Prints', description: 'A smaller edition with the same quiet tension and spring color.', owners: 143, editions: 500, verified: true },
  { id: 'seaport-night', title: 'Seaport Subject / Night', creator: 'Open Editions', creatorHandle: '@open-editions', price: 0.38, displayPrice: '0.38 ETH', category: 'Photography', image: '/assets/seaport-subject.webp', chain: 'Ethereum', tokenId: '#N8', collection: 'Open Editions', description: 'The harbor after the crowds have gone home.', owners: 208, editions: 1000, verified: false },
  { id: 'roboramen-special', title: 'RoboRamen / Midnight', creator: 'RoboRamen', creatorHandle: '@roboramen', price: 2.4, displayPrice: '2.40 ETH', category: 'Collectibles', image: '/assets/RoboRamen.webp', chain: 'Ethereum', tokenId: '#77-M', collection: 'RoboRamen', description: 'The limited midnight shift, served hot and stamped by the chef.', owners: 86, editions: 250, verified: true },
];

export const activity = [
  { type: 'Sale', title: 'Ringers #109', detail: 'sold to 0x4f...a91c', price: '111.20 ETH', time: '12 min ago', image: '/assets/9_ringers_109.webp' },
  { type: 'Bid', title: 'Planet Fall', detail: 'bid by 0x82...19fe', price: '23.70 ETH', time: '38 min ago', image: '/assets/planetfall.avif' },
  { type: 'Listing', title: 'Blue Illusion', detail: 'listed by Pak', price: '7.12 ETH', time: '1 hr ago', image: '/assets/blue_illusion.webp' },
  { type: 'Sale', title: 'Bean #5467', detail: 'sold to 0x11...e40b', price: '0.42 ETH', time: '2 hrs ago', image: '/assets/bean.avif' },
  { type: 'Listing', title: 'RoboRamen / Midnight', detail: 'listed by RoboRamen', price: '2.40 ETH', time: '3 hrs ago', image: '/assets/RoboRamen.webp' },
  { type: 'Bid', title: 'FIJI / Afterlight', detail: 'bid by 0xa7...b122', price: '0.68 ETH', time: '4 hrs ago', image: '/assets/fiji.avif' },
  { type: 'Sale', title: 'Oni Sakura / Print', detail: 'sold to 0xc1...7720', price: '0.72 ETH', time: '5 hrs ago', image: '/assets/oni.png' },
];

export const getItem = (id) => marketplaceItems.find((item) => item.id === id);
export const categories = ['All', ...new Set(marketplaceItems.map((item) => item.category))];
